wheel1_joint_velocity_controller:
  ros__parameters:
    type: "velocity_controllers/JointVelocityController"
    joint: "wheel1_joint"
    command_interface: "velocity"
    pid:
      p: 5.0
      i: 0.0
      d: 0.0

wheel2_joint_velocity_controller:
  ros__parameters:
    type: "velocity_controllers/JointVelocityController"
    joint: "wheel2_joint"
    command_interface: "velocity"
    pid:
      p: 5.0
      i: 0.0
      d: 0.0

wheel3_joint_velocity_controller:
  ros__parameters:
    type: "velocity_controllers/JointVelocityController"
    joint: "wheel3_joint"
    command_interface: "velocity"
    pid:
      p: 5.0
      i: 0.0
      d: 0.0

wheel4_joint_velocity_controller:
  ros__parameters:
    type: "velocity_controllers/JointVelocityController"
    joint: "wheel4_joint"
    command_interface: "velocity"
    pid:
      p: 5.0
      i: 0.0
      d: 0.0
